logging:
  level:
    ROOT: info
    org:
      hibernate:
        type: trace
        
spring:
   devtools:
      livereload:
         enabled: true
   datasource:
      driverClassName: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://localhost:3306/test
      username: root
      password: rh19ehf
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
   thymeleaf:
      check-tmplate-location: true
      prefix: /WEB-INF/page/
      suffix: .html
      mode: HTML5
      cache: false
      order: 0
   logging:
     level:
       org.springframework.security: DEBUGG